from misc.enums import ORDER_TYPES

API_KEY = 'A3tAa73riGfwRGRWWHFqnwXa19EltT25Uhvcyu29ML7OlZ1YtE8UYAObqmSjQ09g'
API_SECRET = 'pvoK7pd3tCn2ggBTJy93JMFRqNCo4JxHoRV5tRHuK4YAMzb49DvXzmPmJPlQikpx'

ENVIRONMENT = "RE"

CHECKER_API_REQUEST_THREAD_MAX_COUNT = 1
CHECKER_API_REQUEST_MIN_TICK = 45

TARGET_SYMBOL = 'PORTOUSDT'

BALANCE = 200.0

INCREMENTAL_ORDER_LIMIT_PRICE_MULTIPLIER = 1.25
INCREMENTAL_ORDER_LIMIT_PRICE_MAX = 5.0

STATIC_LIMIT_ORDER_PRICE = 5.0

ORDER_TYPE = ORDER_TYPES.ORDER_TYPE_STATIC_LIMIT
ORDER_QUANTITY_BOTTLENECK_MULTIPLER = 1.0
ORDER_PRICE_MAX_DECIMALS = 4
ORDER_COUNT = 1
